openapi: 3.0.0
info:
  title: Patients API
  description: "A simple patients API for testing purposes"
servers:
  - url: http://localhost:4000

produces:
  - application/json

paths:
  /patients:
    get:
      summary: "Returns a list of patients"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  name:
                    type: string
                  age:
                    type: number
                  city:
                    type: string
                example:
                  - name: John
                    age: 13
                    city: Lisbon
                  - name: Albert
                    age: 45
                    city: LA
    post:
      summary: "Create a new User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: number
                city:
                  type: string
              example:
                name: Test
                age: 99
                city: Test  
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                message:
                  type: string
                example:
                  message: "User Created"



