openapi: 3.0.0
info:
  title: Patients API
  description: "A simple patients API for testing purposes"
servers:
  - url: http://localhost:4000

produces:
  - application/json

paths:
  /patients:
    get:
      summary: "Returns a list of patients"
      responses:
        '200':
          description: "OK"
          schema:
            type: object
            properties:
              patients:
                type: array
                items:
                  name:
                    type: string
                  age:
                    type: number
                  city:
                    type: string
            example:
              patients:
                - name: Teste
                  age: 99
                  city: Cidade



